"""create catalog_models table

Revision ID: 0013_create_catalog_models
Revises: 0012_add_files_cleaned_flag
Create Date: 2026-05-23 00:00:00

Per-shop device templates (номенклатура): default specs + photos for a
model so the purchase wizard can pre-fill instead of re-typing (CLAUDE.md
§6, §15). Hand-written rather than autogenerated — Alembic's server-default
comparison can't diff the existing ``json`` columns ("operator does not
exist: json = unknown").
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0013_create_catalog_models"
down_revision: str | None = "0012_add_files_cleaned_flag"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "catalog_models",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column(
            "shop_id",
            sa.Integer,
            sa.ForeignKey("shops.id", name="fk_catalog_models_shop_id"),
            nullable=False,
            index=True,
        ),
        sa.Column("category", sa.String(16), nullable=False),
        sa.Column("brand", sa.String(80), nullable=False),
        sa.Column("model", sa.String(120), nullable=False),
        sa.Column(
            "default_specs", sa.JSON, nullable=False, server_default="{}"
        ),
        sa.Column("photos", sa.JSON, nullable=False, server_default="[]"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.UniqueConstraint(
            "shop_id", "category", "brand", "model", name="uq_catalog_shop_model"
        ),
    )
    op.create_index(
        "ix_catalog_shop_brand", "catalog_models", ["shop_id", "brand"]
    )


def downgrade() -> None:
    op.drop_index("ix_catalog_shop_brand", table_name="catalog_models")
    op.drop_table("catalog_models")
