"""add tenants table and user.tenant_id, role

Revision ID: 49fabfdbeb26
Revises: f70a674c3c35
Create Date: 2026-05-28 22:32:37.970760

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '49fabfdbeb26'
down_revision: str | None = 'f70a674c3c35'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(length=32), server_default='owner', nullable=False))
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_tg_username'), 'users', ['tg_username'], unique=False)
    op.create_foreign_key(
        'fk_users_tenant_id_tenants', 'users', 'tenants',
        ['tenant_id'], ['id'], ondelete='RESTRICT',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_users_tenant_id_tenants', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_tg_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_column('users', 'tenant_id')
    op.drop_table('tenants')
    # ### end Alembic commands ###
